repos:
-  repo: local
   hooks:
   -  id: vet
      name: go vet
      language: system
      entry: go vet  ./...
      pass_filenames: false
      types: [go]
   -  id: lint
      name: golangci
      language: system
      entry: golangci-lint run
      pass_filenames: false
      types: [go]
   -  id: prettier
      name: prettier
      files: '^webui/'
      language: system
      entry: webui/node_modules/.bin/prettier --check
      pass_filenames: true
      types: [javascript]
